services:
  db:
    image: postgres:latest
    container_name: pg_jwtsecurity
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_jwtsecurity
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  pg_data: